name: Deploy Ericcole

on:
  push:
    branches: [test, main]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy-test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy TEST
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 38.180.190.159
          username: root
          port: 22
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: /usr/local/bin/deploy_ericcole_test.sh

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy PROD
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 38.180.190.159
          username: root
          port: 22
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: /usr/local/bin/deploy_ericcole_prod.sh
